### ISSUE TITLE
Setting for Lefties (or people with only a right arm) - flip screen by 180°

### ISSUE THREAD

**Issue by FenellaKW** [InfiniTimeOrg/InfiniTime#1335] opened 2022-09-19 17:10 UTC
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

A checkbox in the settings to to turn on left-handed mode.

### Description

When worn on your right arm your hand is constantly pressing the button when you move your wrist. 
If the screen could be flipped by 180 degrees, the watch could be warn on your right hand with the button to point towards your elbow rather than hand.

**Comment by minacode** [comment] 2022-09-19 21:34
#1098

**Comment by JF002** [comment] 2022-09-27 15:46
Yes, duplicate of #1098

**Closed by JF002** 2022-09-27 15:46 UTC
Labels: feature request
