### ISSUE TITLE
Design Guidelines

### ISSUE THREAD

**Issue by PhilDevProg** [InfiniTimeOrg/InfiniTime#892] opened 2021-12-27 23:23 UTC
We need detailed design guidelines for InfiniTime so developers can develop more consistently. Something like what GNOME has with the Human Interface Guidelines.

**Comment by Riksu9000** [comment] 2021-12-29 15:25
There are some guidelines here https://github.com/InfiniTimeOrg/InfiniTime/blob/develop/doc/ui_guidelines.md

Generally the default theme and included fonts can be used in apps. Is there something that you think it's missing?

**Comment by PhilDevProg** [comment] 2021-12-30 09:54
@Riksu9000 In fact, I don't know... 😅 @Avamander  told me to open this issue.

**Comment by Avamander** [comment] 2021-12-30 09:56
The incompleteness of UI design guidelines was brought up in an another thread, I indeed told to solve that in a new issue.

**Comment by Riksu9000** [comment] 2022-01-22 12:04
@PhilDevProg Well, I still don't know what the issue is, so unless you have something to add, we can close this and let someone that finds an issue with the guidelines open an issue.

**Comment by PhilDevProg** [comment] 2022-01-22 12:05
> @PhilDevProg Well, I still don't know what the issue is, so unless you have something to add, we can close this and let someone that finds an issue with the guidelines open an issue.

Okay

**Closed** 2022-01-22 12:05 UTC
Labels: enhancement
