### ISSUE TITLE
Drop down list: scrollbar goes over the edge

### ISSUE THREAD

**Issue by PhilDevProg** [InfiniTimeOrg/InfiniTime#953] opened 2022-01-22 21:57 UTC
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

The scrollbar goes over the edge in the drop down list of the metronome app 

### What should happen instead?

The scrollbar shouldn't go over the edge.

### Reproduction steps

I open the metronom app.
I press the button with the text "4 bpb".
I scroll down the list to the bottom.
The scrollbar goes over the edge here:
![IMG_20220122_225015_1](https://user-images.githubusercontent.com/91820316/150656672-7506a9e1-519e-4aa0-91e6-6efdbc1d6069.jpg)

### Version

1.8.0

**Comment by JF002** [comment] 2022-03-13 16:32
I guess this bug is related to LVGL (the UI lib used in InfiniTime) and not directly to InfiniTime. 

Unless someone is willing to write a patch for LVGL, this bug might be fixed in a future/more recent version of LVGL, but I don't know when we'll update LVGL in InfiniTime.

**Comment by Riksu9000** [comment] 2022-03-13 16:44
This issue is at least partially caused by incorrect theme configuration in InfiniTime.

**Comment by JF002** [comment] 2022-03-13 18:38
> This issue is at least partially caused by incorrect theme configuration in InfiniTime.

Oh really? I'll re-open it, then!

**Closed** 2022-05-08 11:21 UTC
Labels: bug
