### ISSUE TITLE
Text disappears from watchface on chimes

### ISSUE THREAD

**Issue by Xorger** [InfiniTimeOrg/InfiniTime#2089] opened 2024-07-07 06:22 UTC
### Verification

- [X] I searched for similar bug reports (including closed issues) and found none was relevant.

### What happened?

All text disappears from watchface on chimes with external resource watchfaces (Casio G7710 and the Infinineat face)

### What should happen instead?

I was expecting to see the time and other data on the watchface.

### Reproduction steps

* Switch watchface to the Casio G7710 or Infinineat faces
* Enable chimes
* Wait for the chime (or change the time if you're impatient
* Time and other data disappears

### More details?

Switching to a different screen (e.g. notifications fixes the issue until the next chime
Here's a really bad photo:
![Photo on 7-7-2024 at 4 09 pm #2](https://github.com/InfiniTimeOrg/InfiniTime/assets/112749251/de07971d-fa6b-47a4-b993-5c236c458d1b)

### Version

1.14.0

**Comment by FintasticMan** [comment] 2024-07-07 09:22
Duplicate of #1411, has been fixed in the main branch, so the fix will be included in 1.15.

**Closed by FintasticMan** 2024-07-07 09:22 UTC
Labels: bug
