### ISSUE TITLE
Find my phone option

### ISSUE THREAD

**Issue by AndriiZ** [InfiniTimeOrg/InfiniTime#598] opened 2021-08-18 09:18 UTC
It would be great to search lost phone from the watch. I dont know if any companion app support this feature

**Comment by tmilburn** [comment] 2021-08-23 17:38
Gadgetbridge has the required activity which can be triggered https://github.com/Freeyourgadget/Gadgetbridge/blob/df44b798c91d832d1ae05821c860decc5ba8ac93/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/FindPhoneActivity.java but it requires code to be added to the pinetime device support in https://github.com/Freeyourgadget/Gadgetbridge/blob/d951ab1da7c4e08241eb25938f99cbe884fbb74d/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pinetime/PineTimeJFSupport.java and a way of triggering this from the watch. I would suggest a new service for this with a characteristic to start and stop finding the phone.

**Comment by Avamander** [comment] 2021-08-23 17:44
> I would suggest a new service for this with a characteristic to start and stop finding the phone.

Standard has an immediate alert characteristic for exactly this purpose.

**Comment by tmilburn** [comment] 2021-08-23 17:59
Isn't the immediate alert service for finding a device (peripheral) rather than a phone (central) since it has a single write characteristic.

**Comment by Avamander** [comment] 2021-08-23 18:35
Both sides can expose services and characteristics.

**Comment by Avamander** [comment] 2021-10-02 19:22
Duplicate of https://github.com/InfiniTimeOrg/InfiniTime/issues/543

**Closed** 2021-10-02 19:23 UTC
Labels: feature request
