### ISSUE TITLE
Alert when out of Bluetooth range

### ISSUE THREAD

**Issue by ryantrinkle** [InfiniTimeOrg/InfiniTime#1289] opened 2022-08-16 22:05 UTC
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

I'd like my watch to alert me when it has lost connection to my phone

### Description

One of the reasons I wear a PineTime is that I want to be very sure to get all my notifications.  However, if it has lost connection to my phone, it can't do that.  It would be great if my PineTime can let me know about this so I can fix it.

This applies in a few situations:
- If I've accidentally left my phone behind
- If my phone ran out of batteries
- If my phone's bluetooth is disabled

Although in some cases this may be intentional (e.g. turning on airplane mode, rebooting phone, purposely leaving the phone behind), I don't think getting a single alert would be too annoying.  Alternatively, this could be a configurable setting.

**Comment by Riksu9000** [comment] 2023-02-20 06:58
Duplicate of #772

**Closed by Riksu9000** 2023-02-20 06:58 UTC
Labels: feature request
