### ISSUE TITLE
[BUG] Watch will vibrate throughout the phone conversation

### ISSUE THREAD

**Issue by ajack2001my** [InfiniTimeOrg/InfiniTime#650] opened 2021-09-07 03:34 UTC
When I get a phone call, the watch will vibrate. It will vibrate till the call ends. I can imagine the battery dying pretty quickly if I was on an hour long call... Annoying too...  Anyways, not sure if it's a bug or me not doing the settings right. Using InfiniTime 1.4.0 and GadgetBridge 0.59.2 on a Samsung Note 9.

**Comment by calhix** [comment] 2021-09-07 03:36
I believe a duplicate of #591.

**Comment by MaWalla** [comment] 2021-09-07 14:33
I'd like to add that I got a phone call today I couldn't take because I was driving the car. The watch kept the display on and vibrated as intended, but continued even after the call stopped until I pressed the button on the side. I guess that when the call is either taken or stopped, the watch should also stop vibrating.

I'm on GadgetBridge 0.59.2 too, but using a OnePlus 6T with crDroid (LineageOS based / Android 11)

**Comment by evergreen22** [comment] 2021-09-07 16:26
See the comment by @Riksu9000 on commit [1635bfa](https://github.com/JF002/InfiniTime/commit/1635bfafb3fe9dce1ab05102d1bfeac1eca81c66) in 1.4.0 for the close screen problem on a call.

**Comment by ajack2001my** [comment] 2021-09-27 08:34
Using InfiniTime 1.5.0 now, problem still persist... :/

**Comment by Avamander** [comment] 2021-10-02 18:59
Duplicate of https://github.com/InfiniTimeOrg/InfiniTime/issues/591

**Closed** 2021-10-02 18:59 UTC
