### ISSUE TITLE
Low battery warning and inminent power down

### ISSUE THREAD

**Issue by adocampo** [InfiniTimeOrg/InfiniTime#761] opened 2021-10-18 22:58 UTC
It happened again... my alarm didn't start because the watch's battery was drained in the middle of the night.
I would really love my watch to warn when it detects it's running out of battery and make sure I noticed it.
I would recommend the way pebble did, a long vibration and changing the watchface into a notice indicating an approximate time frame when it will be exhausted (i.e.: morning, afternoon, evening or night)

![imagen](https://user-images.githubusercontent.com/2266612/137816844-38ea0909-bd83-4fb8-a35a-f97c074642c4.png)

That watchface will stay there until the user manually acknowledges by pressing the back button, so the users can bear in mind they need to charge it before that timeframe.

As a bonus, when the power down is imminent, another simple watchface (and a vibration) should be shown, and the user wouldn't be able to do anything with but charge it or power the watch off.

![imagen](https://user-images.githubusercontent.com/2266612/137817254-a81f97c7-6064-46ca-974f-45e2ffdc64e3.png)

As a last resort, watch should power itself down with a tiny percentage of battery to let the clock and alarms live for a while instead of completely exhaust the battery and force the users to re-pair the watch again in order to get the time and date back.

**Comment by adocampo** [comment] 2021-10-20 18:55
> A companion app giving a warning would also be nice.

Agree, yet I'm not very aware of the phone's notifications as usually have it away from me. Anyway, I would open an issue for that on [Gadgetbridge's issue tracker](https://codeberg.org/Freeyourgadget/Gadgetbridge/issues), or in [Siglo's one](https://github.com/alexr4535/siglo/issues), to let them know there are interest from people to develop more features for pinetime/infinitime

**Comment by Riksu9000** [comment] 2023-01-30 12:31
Duplicate of #659

**Closed as not planned by Riksu9000** 2023-01-30 12:31 UTC
Labels: feature request
