### ISSUE TITLE
Ability to clear notifications

### ISSUE THREAD

**Issue by GIJack** [InfiniTimeOrg/InfiniTime#272] opened 2021-04-17 01:18 UTC
I am requesting adding a feature to clear notifications after they are read. Perhaps a swipe to the right?

**Comment by JF002** [comment] 2021-04-17 08:23
That would be a nice improvement, indeed. As far as I know, the standard Alert Service protocol does not provide this feature. We'll probably have to define a new BLE API for that.

**Comment by GIJack** [comment] 2021-04-17 15:57
Can just a clear buffer command that clears them locally? I mean wasp os does this already.

But a BLE API to acknowledge alerts on the watch without having to remove the phone from your pocket would be super sweet.

**Comment by Avamander** [comment] 2021-04-17 16:01
> That would be a nice improvement, indeed. As far as I know, the standard Alert Service protocol does not provide this feature. We'll probably have to define a new BLE API for that.

This can theoretically be lifted from the Pebble notification protocol and its GB implementation to a large extent. Currently GB keeps track of what notifications on the phone are dismissed and dismisses them from the Pebble, it wouldn't be too difficult to create a two-way sync.

First step would be making it possible to assign an unique ID for each notification on the watch. Second step would be a way to both update and delete notifications by ID.

**Comment by JF002** [comment] 2021-04-17 16:06
> Can just a clear buffer command that clears them locally? I mean wasp os does this already.
Yes, indeed, we could begin with clearing the notifications locally !

To acknowledge notifications from the watch, @Avamander is right!

**Comment by petterhs** [comment] 2021-04-20 14:05
Related to #176 

Is the goal just to remove the notification only on the device or to also clear it from the phone?

**Comment by pfeerick** [comment] 2021-04-21 08:28
Since the comparison is made with wasp-os, I think it's just clear locally, which is done on wasp-os by pulling down the notification screen done one more time once all the notifications are shown, and it then asks if you want to clear them or not.

**Comment by GIJack** [comment] 2021-04-21 21:45
Both actually. My primary concern is being able to clear locally like wasp OS.

That said, I would like as a stretch goal to clear the notification on the phone. I mean, my goal for a smartwatch is just a remote control for a smartphone that also tells time.

**Comment by Avamander** [comment] 2021-10-02 20:25
I'll consider this a duplicate of https://github.com/InfiniTimeOrg/InfiniTime/issues/272. Syncing dismissals to companion phone should probably be a separate issue, if there's any need for that.

**Closed by Avamander** 2021-10-02 20:25 UTC
Labels: enhancement

**Comment by pfeerick** [comment] 2021-10-03 01:32
It's a duplicate of itself?
