### ISSUE TITLE
The time should be updated before waking up the display

### ISSUE THREAD

**Issue by Avamander** [InfiniTimeOrg/InfiniTime#72] opened 2020-10-02 23:22 UTC
The time should be updated before waking up the display. Right now it quickly flickers to the correct time, this wastes a tiny amount of time and energy drawing the wrong number. This should be improved primarily just for polish.

**Comment by petterhs** [comment] 2021-04-20 13:31
I don't think this is the case anymore. Could be closed

**Comment by christianfl** [comment] 2021-05-19 21:46
I can confirm that for the digital clock @petterhs (which was afaik the only watch face when this issue was created). However, the analog watch face introduced in InfiniTime 0.15.0 does show the old time for a few ms after waking up the clock. The amount of time is so little that I couldn't record it with my smartphone but it is there and noticeable. Happens with InfiniTime 1.0.0.

**Comment by tmilburn** [comment] 2021-08-19 19:06
I think this is due to the LCD being woken up before the current app screen is refreshed. The LCD's frame memory appears not to be erased during a soft or hard reset which causes it to display the last screen when switched on. The app then refreshes the screen but in the case of the analog watch face this takes 10s of milliseconds causing the last screen to be briefly visible.

A possible fix would be to run a single refresh of the current app screen before turning on the display such that the LCD's frame memory is updated.

**Comment by Riksu9000** [comment] 2021-08-19 19:34
>I think this is due to the LCD being woken up before the current app screen is refreshed. The LCD's frame memory appears not to be erased during a soft or hard reset which causes it to display the last screen when switched on. The app then refreshes the screen but in the case of the analog watch face this takes 10s of milliseconds causing the last screen to be briefly visible.

It is most likely caused by something like this as #586 seems to fix this issue.

**Comment by tmilburn** [comment] 2021-08-19 19:47
I'm surprised that #586 fixes the issue because that PR only removes unnecessary commands to the LCD. The display still comes on before the app is refreshed.

**Comment by Riksu9000** [comment] 2021-09-04 09:56
The display takes some time to wake up after the Sleep Out command and it displays two blank frames. I think we're intended to update the screen during this blank period, but the commands added so much delay that it couldn't update the display in time, so it displayed what was left previously. Therefore I think this issue can be closed with #586.

**Comment by watchdominiondotcom** [comment] 2021-09-28 18:41
the time does not sync it says 1978. does it just not work or did i not figure it out?

**Comment by JF002** [comment] 2021-12-27 20:09
Latest versions of InfiniTime (1.7) improved many aspect of the UI and UX. I think we can close this issue. Feel free to reopen if needed.

**Closed by JF002** 2021-12-27 20:09 UTC
Labels: enhancement
