### ISSUE TITLE
InfiniTime App Store

### ISSUE THREAD

**Issue by ajack2001my** [InfiniTimeOrg/InfiniTime#1380] opened 2022-10-19 02:07 UTC
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

User ability to add/remove/update apps and watchfaces

### Description

With InfiniTime now having an external storage system, I believe it's time users get to customize and personalize the watches.

**Comment by minacode** [comment] 2022-10-19 06:50
> I believe it's time

So does everyone, but have you read anything on how difficult that is? If you know how to do this, you are welcome to contribute though 😉

**Comment by InFerYes** [comment] 2022-10-19 09:36
Is it a matter of having a page with previews and links to resource zips? Should not be too dificult, but is probably out of scope of this project.

**Comment by minacode** [comment] 2022-10-19 09:46
As far as I get it, it is a matter of: "How do you load apps?" This firmware is based on FreeRTOS. It's does not have processes. It is all compiled to a single binary.

**Comment by minacode** [comment] 2022-10-19 09:58
Maybe I am misreading it, but the issue sounds a little demanding. It's not time that anyone gets anything. People here do good work and you are welcome to help. Your wish for this feature is valid though. And a duplicate of at least #1262.

**Comment by Avamander** [comment] 2022-10-19 13:38
In general I do agree that this is something that should be made once we have a method of updating only segments of the firmware. But I do not think this is an InfiniTime (as the *firmware*) issue, neither do I think this is happening any time soon.

I will close this issue for those two reasons here for now.

**Closed by Avamander** 2022-10-19 13:38 UTC
Labels: feature request

**Comment by ajack2001my** [comment] 2022-10-20 02:30
> Maybe I am misreading it, but the issue sounds a little demanding.

Sorry if my enthusiasm is seen as "a little demanding", I just wanted it requested someplace and hope for best for this device. I can even accept the "if you want it, code it" mentality of open source but to say I was demanding. That saddens me.  Maybe I should just shut up and take what I can get from this project as deem fit by you guys.

After all, beggars can't be choosers... :/

**Comment by minacode** [comment] 2022-10-20 08:58
I apologize. I am sorry I misunderstood you and did not mean to shut you down for raising a feature request. It is obviously fine to do them and I always want to support people interacting with the project.

**Comment by JF002** [comment] 2022-10-26 20:39
@ajack2001my Thank you for your enthusiasm about InfiniTime and the new features :-)

As always on the internet, it's not easy to grasp the intent and the tone of a written message, and I thank you all for staying polite and trying to understand each others !

So, yes, if we look far ahead, this is of course a good idea. But... even if the resource feature is a nice step towards "installable apps", we are unfortunately still very far from this milestone. In this current state, InfiniTime is only able to read "static" data from the resources, fonts and images mostly. 
It probably not obvious, but a lot of work is still needed to eventually be able to build, package, store, load and execute applications from the resources.

**Comment by Idcrafter** [comment] 2023-10-18 14:43
wouldn't it be possible if the watchfaces aren't normal code but with a config/layout file that instructs the OS to display the Time and other icons at relative location and scales would make it possible and with the showcase would a dev make a a small github repo or a message with the config/layout file and a screenshot of how it looks?  this will probably not work for applications but this might make hotswaping of watchfaces possible (the default one will probably be needed till it loads the faces completely after a swap/reboot if loading would be too slow) .
