### ISSUE TITLE
Dismiss call screen when call is answered on the phone

### ISSUE THREAD

**Issue by The-Linux-User** [InfiniTimeOrg/InfiniTime#899] opened 2021-12-31 15:40 UTC
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Dismiss call screen when call is answered on the phone

### Description

Would it be possible to dismiss the call screen on the watch when I accept (or dismiss) the call on my phone? Currently I have to press the watch button after answering a call on the phone, else the watch won't stop vibrating.
This would greatly improve the UX since it can be annoying to reach for your watch in addition to your phone every time someone calls

**Comment by Riksu9000** [comment] 2022-01-01 14:40
Duplicate of #367

**Closed by Riksu9000** 2022-01-01 14:40 UTC
Labels: feature request
