### ISSUE TITLE
Refactor watch faces

### ISSUE THREAD

**Issue by minacode** [InfiniTimeOrg/InfiniTime#1353] opened 2022-10-03 16:42 UTC
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Refactor the watch face classes

### Description

Watch faces are written by being copied :grinning:. This shows that there is a lot of potential to refactor some code. It would also make writing watch faces even easier. I think an abstract class WatchFace would be the solution.
* Watch faces take the same parameter in their constructors. We can probably use the (appropriate) same for all.
* Watch faces handle meters and refresh their values. It is the same code in every one of them.

**Comment by Avamander** [comment] 2022-10-04 10:14
Duplicate of https://github.com/InfiniTimeOrg/InfiniTime/issues/431

**Closed by Avamander** 2022-10-04 10:14 UTC
Labels: help wanted, feature request
