### ISSUE TITLE
Paddle/Pong - ball should not run along upper/lower wall boundaries

### ISSUE THREAD

**Issue by Danimations** [InfiniTimeOrg/InfiniTime#1084] opened 2022-04-12 13:43 UTC
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Ball runs parallel/along upper or lower wall sometimes

### What should happen instead?

Ball should bounce at any angle other than parallel with upper or lower wall when at that position

### Reproduction steps

Play the game. When the ball is hit precisely into the corner of the playing field, it sometimes (quite often) bounces off the back wall and travels parallel with the upper or lower wall. Sometimes this effect lasts for several consecutive bounces. While the game remains functional and doesn't trap the player in an infinite loop, this ball behavior feels broken and could be improved.

### More details?

In my opinion this should not happen at all. Broadly speaking, the physics of the game could benefit from some other improvements, but I consider this one to be an actual bug rather than a design issue. I'd like to see it excluded from future versions.

### Version

1.9.0

**Comment by minacode** [comment] 2022-04-12 14:15
I read the code. It seems, that the ball is not kept in the bounds. So it maybe glitches into the upper or lower walls and zig-zags, because each update does `dx *= -1`.
That could seem like parallel, if `dx` is small enough. 
I did not test this.

**Comment by NeroBurner** [comment] 2022-04-15 11:11
does the ball travel "stick" to the upper or lower wall? Or does the ball just travel in a straight height (away from the upper/lower wall)?

The second one could be just the random `dy` introduced by me in https://github.com/InfiniTimeOrg/InfiniTime/pull/797

**Comment by Danimations** [comment] 2022-04-17 12:48
Hi @NeroBurner . Yes, the ball travel "sticks" to the upper or lower wall sometimes... traveling immediately alongside the wall, and rolling parallel to it. I had to play the game long enough to score 32 points or so in order to see this bug repeat a few times.

**Comment by NeroBurner** [comment] 2022-10-18 14:24
good to hear, I was never able to reproduce this bug. Closing for now

**Closed by NeroBurner** 2022-10-18 14:24 UTC
Labels: bug
