### ISSUE TITLE
Pinetime Keeps vibrating after i get phone call

### ISSUE THREAD

**Issue by aazaya** [InfiniTimeOrg/InfiniTime#1047] opened 2022-03-23 20:17 UTC
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

If i get a phone call and if my pinetime is not on silent then it vibrates for eternity until i stop it

### What should happen instead?

I have to keep it on silent but another bug which i have seems to turn on the vibration sometime

### Reproduction steps

every time i get a phone call this happens

### Version

v1.8.0

### Companion app

Gadgetbridge

**Comment by Riksu9000** [comment] 2022-03-23 20:37
Duplicate of #367. Also in the next release the vibration will stop after after a short time. See #903.

**Closed by Riksu9000** 2022-03-23 20:37 UTC
Labels: bug
