### ISSUE TITLE
incoming phone call from gadgetbridge continuously vibrates

### ISSUE THREAD

**Issue by clach04** [InfiniTimeOrg/InfiniTime#812] opened 2021-11-06 19:38 UTC
### 

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

incoming call answered on phone (and hung up) infinitime 1.60 continues to vibrate

### What should happen instead?

should stop vibration when answeerd/hung uo

### Reproduction steps

* call phone
* answer phone, e.g. on handset, car, headphones, etc.
* optional hang up

Watch continues to vibrate

### More details?

Potentially dangerous when driving as dismissing requires looking at watch and taking eyes off road.

### Version

1.60

### Companion app

gadget bridge

**Comment by escoand** [comment] 2021-11-06 19:42
Duplicate of #367

**Comment by geekbozu** [comment] 2021-11-07 01:08
Duplicate closing,
Thanks guys :)

**Closed by geekbozu** 2021-11-07 01:08 UTC
Labels: bug
