### ISSUE TITLE
One touch screen

### ISSUE THREAD

**Issue by randb66** [InfiniTimeOrg/InfiniTime#441] opened 2021-06-19 02:29 UTC
I would like to see together the tilt to wake as well as single touch screen wake up as an option. Not just one or the other but both.

**Comment by Raupinger** [comment] 2021-06-19 04:03
duplicate of #277

**Comment by JF002** [comment] 2021-06-30 18:11
and a PR is already on the work : https://github.com/JF002/InfiniTime/pull/290 :)

**Comment by ThePinkUnicorn6** [comment] 2021-08-07 15:35
I think this can probably be closed now

**Closed** 2021-10-02 18:53 UTC
Labels: duplicate
