### ISSUE TITLE
Gadget Bridge reconnect issue is still halfway alive 

### ISSUE THREAD

**Issue by joseph58tech** [InfiniTimeOrg/InfiniTime#654] opened 2021-09-09 00:03 UTC
On 1.6 the Bluetooth reconnecting issue is fixed, but the only thing that was fixed was when the problem were it would disconnect and not reconnect once a day, BUT the problem were you either turn Bluetooth off or restart your phone and you can't reconnect at all unless you repair the watch still persists

**Comment by ajack2001my** [comment] 2021-09-09 03:44
@joseph58tech Are you using Gadgetbridge 0.59.2?

**Comment by joseph58tech** [comment] 2021-09-09 03:45
Yes

**Comment by chloecormier** [comment] 2021-09-09 06:16
I've had the opposite experience, somehow. With 1.3, I had to remove the device from Gadgetbridge and re-pair it after some time had passed. Now with 1.4, it seems to be reliably staying connected.

In either case, I don't think 1.4 even touched the Bluetooth code, did it? Seeing any change between the two versions is admittedly very weird.

**Comment by toitoinou** [comment] 2021-09-09 06:34
@joseph58tech I have to do the same since I have the pinetime. So same thing in 1.3 and 1.4 for me.
There are currently working on these problems.

**Comment by Avamander** [comment] 2021-09-09 07:27
Duplicate of https://github.com/JF002/InfiniTime/issues/302

**Comment by InFerYes** [comment] 2021-09-18 09:39
> Duplicate of #302
> 
> Search before you open a new issue.

That issue is about switching to airplane mode and then being unable to connect. I think this issue is about losing connection seemingly "randomly". I have this issue. Watch or phone will just stop syncing all of a sudden while the BT adapter was never switched off. It just stops. When I restart the Watch, sometimes it still won't connect and I have to do an annoying dance of re-pairing the watch and restarting it.

**Comment by Avamander** [comment] 2021-09-18 09:45
@InFerYes It's the same issue.

**Comment by InFerYes** [comment] 2021-09-18 09:47
@Avamander You mean it's the same underlying problem.

**Comment by joseph58tech** [comment] 2021-09-29 18:09
OK so infiniTime 1.6 is now released claiming that the BLE was fixed so I will test that out and than close this problem

**Comment by Bugsbane** [comment] 2021-09-30 04:23
Sadly, I still seem to be getting this issue with Infinitime 1.6 and Gadgetbridge 0.59.3  ಠ~ಠ

**Comment by Bugsbane** [comment] 2021-09-30 20:26
Why did this get closed when there's still cases of it happening?

**Comment by Avamander** [comment] 2021-09-30 20:39
> Why did this get closed when there's still cases of it happening?

Because he doesn't have the issue any more.

You can create a new issue that describes exactly on which firmware version, what are the symptoms.

**Comment by joseph58tech** [comment] 2021-10-01 17:30
Sorry for the inconvenience I just experienced half of the original problem and reopened the problem

**Comment by Avamander** [comment] 2021-10-01 17:45
Now it's certainly a duplicate of https://github.com/JF002/InfiniTime/issues/302

**Comment by joseph58tech** [comment] 2021-10-02 18:18
> Now it's certainly a duplicate of https://github.com/JF002/InfiniTime/issues/302

I can see you've been waiting to say thay

**Closed** 2021-10-02 19:17 UTC
