### ISSUE TITLE
After a timeout (~30s?) after screen turns off from inactivity, return to clock face

### ISSUE THREAD

**Issue by sammyj85** [InfiniTimeOrg/InfiniTime#1745] opened 2023-04-16 03:37 UTC
### Verification

- [X] I searched for similar issues and found none was relevant.

### Introduce the issue

If the screen turns off from inactivity (whichever state it ended up), next time you want to use the watch, chances are you want to see the time. So after 30-60s, it should return to the clock face next time the screen wakes up.

### Preferred solution

The screen turns off after 15s of inactivity for me.
After 30s of inactivity, it should set the state to clock face.
Not sure if the micro goes to sleep at the same time the screen turns off, but it could set a timestamp of when the screen turned off. And when it wakes, it compares if more than 15s have passed since the timestamp, in which case it returns to the clock face, before displaying anything.

### Version

1.12.0

**Comment by Riksu9000** [comment] 2023-04-16 11:47
Duplicate of #570. The currently relevant issues are #618 and/or #1592.

**Closed by Riksu9000** 2023-04-16 11:47 UTC
