### ISSUE TITLE
Heart rate always shows zero after screen lock

### ISSUE THREAD

**Issue by FirstWithThisName** [InfiniTimeOrg/InfiniTime#1794] opened 2023-07-07 14:00 UTC
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

When I unlock the screeb the heart rate is always zero.

### What should happen instead?

It should show the last measured value

### Reproduction steps

Unlock the screen, wait until the measuring is done and a value other than zero appiers.

Lock and unlock the screen, and the value is zero again.

### Version

v1.13.0

**Comment by SteveAmor** [comment] 2023-07-07 15:32
This looks to be a duplicate of #1784

**Comment by FirstWithThisName** [comment] 2023-07-08 06:24
@SteveAmor that is true. I don't check closed Issues.
But thy is it closed?

**Comment by ajira86** [comment] 2023-07-10 09:30
As mentioned in first reply of #1784, this subject is related to issue #183

**Closed** 2023-07-10 18:24 UTC
Labels: bug
