### ISSUE TITLE
CI build fails on "extract DFU" when build step fails

### ISSUE THREAD

**Issue by NeroBurner** [InfiniTimeOrg/InfiniTime#1421] opened 2022-11-06 20:47 UTC
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

The firmware build fails in the build step, but has a "succeeded" status, the extract DFU later fails

### What should happen instead?

on build error the build step should indicate the failure

### Reproduction steps

create a PR with a build error in it

For example: https://github.com/InfiniTimeOrg/InfiniTime/actions/runs/3400890559/jobs/5664064903 of 

### More details?

Build step errors, but gets a "checked" symbol
```
/__w/InfiniTime/InfiniTime/src/systemtask/SystemTask.cpp:372:24: error: 'class Pinetime::Applications::DisplayApp' has no member named 'HideIgnoreTouchPopup'
  372 |             displayApp.HideIgnoreTouchPopup(true);
      |                        ^~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [src/CMakeFiles/pinetime-mcuboot-recovery.dir/build.make:706: src/CMakeFiles/pinetime-mcuboot-recovery.dir/systemtask/SystemTask.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:388: src/CMakeFiles/pinetime-mcuboot-recovery.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
+ return 1
+ BUILD_RESULT=1
+ '[' '' '!=' true -a 1 == 0 ']'
0s
```

Then the "Unzip DFU package` step fails
```
Run unzip ./build/output/pinetime-mcuboot-app-dfu-*.zip -d ./build/output/pinetime-mcuboot-app-dfu
unzip:  cannot find or open ./build/output/pinetime-mcuboot-app-dfu-*.zip, ./build/output/pinetime-mcuboot-app-dfu-*.zip.zip or ./build/output/pinetime-mcuboot-app-dfu-*.zip.ZIP.

No zipfiles found.
```

### Version

develop

**Comment by cybuzuma** [comment] 2022-11-25 22:39
duplicate of #1292

**Closed** 2022-11-29 13:03 UTC
Labels: bug
