### ISSUE TITLE
Vibration settings for notifications

### ISSUE THREAD

**Issue by MaWalla** [InfiniTimeOrg/InfiniTime#644] opened 2021-09-04 15:36 UTC
I sometimes happen to not notice the vibration on my wrist when receiving a notification. It would be great to have a seperate setting for vibration length/strength and possibly even patterns.

**Comment by Riksu9000** [comment] 2023-01-16 15:25
Duplicate of #210

**Closed by Riksu9000** 2023-01-16 15:25 UTC
Labels: feature request
