### ISSUE TITLE
RFC: Timeline event packing

### ISSUE THREAD

**Issue by Avamander** [InfiniTimeOrg/InfiniTime#1878] opened 2023-10-06 14:43 UTC
Problem:
It's somewhat difficult to handle long-term and short-term events overlapping in the timeline in user-facing situations.

Proposal:
Some of this confusion can be removed by implementing predictable conflict resolution. 

We can adjust the `timestamp` value of the longer event to start at the end of shorter/previous element's `timestamp + expiration` and shorten expiration of the longer event by the amount shortened.

This packing shouldn't be done for equally-long events, neither should a shorter event be shortened.

Before:
```
|     |     |     |     |     |     |     |     |     |
|────────────────────────────────────────────────────────────►
  ┌───────────┐
  │Temperature│
  └───────────┘
     ┌────────────────────────────────────────────────┐
     │ Temperature (long-term)                        │
     └────────────────────────────────────────────────┘
```
After:
```
|     |     |     |     |     |     |     |     |     |
|────────────────────────────────────────────────────────────►
  ┌───────────┐┌──────────────────────────────────────┐
  │Temperature││ Temperature (long-term)              │
  └───────────┘└──────────────────────────────────────┘
```

Are there any potential use-cases where this might not work out as intended?

**Comment by minacode** [comment] 2023-10-07 10:47
> It's somewhat difficult to handle long-term and short-term events overlapping in the timeline in user-facing situations.

Can you explain more, what exactly the problem is?

**Comment by JF002** [comment] 2023-12-23 20:51
Thanks for your work @Avamander. However, I decided to rework the weather service to fix the issues more easily, so I'll close this one in favor of #1924.

**Closed by JF002** 2023-12-23 20:51 UTC
Labels: weather
