### ISSUE TITLE
Step count is lost between reboots

### ISSUE THREAD

**Issue by slm85kbh** [InfiniTimeOrg/InfiniTime#1478] opened 2022-12-07 09:37 UTC
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Storage of logged steps between reboots of the watch

### Description

It would be nice if the logged steps are stored in NVM, because if the watch is rebooted without syncing first, the logged steps are lost.

I don't know if it is a bad idea for the lifetime of the flash, but it might be implemented so that the logged steps are written every 5-10-15 minutes for example, or simple wear-leveling could be implemented.

**Comment by JF002** [comment] 2022-12-07 19:43
I think we have 2 options here :
 - Store the steps in NVM. Since we are using LittleFS, we do not have to worry about wear leveling, as LFS takes care of it. Not sure how it'll impact the lifetime of the flash chip, though.
 - At boot time, do not reset the motion sensor if it's already initialized. This way, the step count won't be reset in the chip and InfiniTime won't have to store the value in NVM.

**Comment by slm85kbh** [comment] 2022-12-08 12:19
I see, I would clearly go for option 2, as a watch reset rarely involves a disconnection of the power supply in a sealed watch. Except when it goes completely flat, but I don't think there's need to account for that. 
It could be mitigated by only storing the step data when the battery is under 10% for example (when the new curve is implemented).
And this method also doesn't put any strain on the flash. 
I haven't looked into the code yet, and I'm fairly new to GIT, so I might not be able to do a PR yet :)

**Comment by HumanG33k** [comment] 2022-12-31 21:54
I think it can permit to sync less the watch with companion app. 
sync only 1 time a week look good  for me as user.

**Comment by Riksu9000** [comment] 2023-01-16 15:05
Duplicate of #493

**Closed by Riksu9000** 2023-01-16 15:05 UTC
Labels: enhancement
