### ISSUE TITLE
Add US date format to the G7710 watch face in 24-hour mode

### ISSUE THREAD

**Issue by smccloud** [InfiniTimeOrg/InfiniTime#1381] opened 2022-10-19 14:02 UTC
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Add US date format to the G7710 watch face in 24-hour mode

### Description

I will be purchasing a PineTime shortly and like the looks of the G7710, however, I prefer 24-hour time.  Reading the news in Discord, this forces the PineTime to use the European date format, which I can convert but there is a good chance I will make a mistake.  If possible, I would like to be able to set it to the US date format of MM-DD instead of the European date format of DD-MM.

**Comment by Riksu9000** [comment] 2023-01-13 06:14
Duplicate of #1166

**Closed by Riksu9000** 2023-01-13 06:14 UTC
Labels: feature request
