### ISSUE TITLE
Music app, track text scrolls too fast with longer track titles.

### ISSUE THREAD

**Issue by dns53** [InfiniTimeOrg/InfiniTime#130] opened 2020-11-09 01:28 UTC
When using the music app on the watch the track artist and track name are displayed.
I have a track name with a longer than will display on the screen so this text is automatically scrolling forwards and backwards.

This seems to be moving the text forwards and backwards one character each frame with this appearing to update more than 20 characters each second making it hard to read.

Could we change the update speed of the text so the text updates at a more easy to read rate such as moving the text forward or backwards a character every second, every half second etc.

**Comment by Avamander** [comment] 2020-11-09 08:55
Duplicate of https://github.com/JF002/Pinetime/issues/97

**Comment by pfeerick** [comment] 2021-05-12 11:44
This can be closed as was fixed in #259.

**Comment by MysteriousLog6** [comment] 2021-06-11 06:02
prithee closeth this issue f'r t doest the not existeth anym're @JF002

**Closed** 2021-10-02 18:30 UTC
Labels: duplicate
