### ISSUE TITLE
steps count reset on restart

### ISSUE THREAD

**Issue by dozadoesit** [InfiniTimeOrg/InfiniTime#1072] opened 2022-04-05 17:30 UTC
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

steps get reset to 0 on restart

### What should happen instead?

steps count should be retained

### Reproduction steps

on version 1.8 I notice anytime I reboot I lose all my steps. This is a problem because if you are trying to track steps in an app you run into the issue of how to handle this situation. 

### More details?

In my own app I am trying to add the steps together and keep track of the differences but it's a workaround not a solution. I was also thinking of allowing my app to write back the correct number of steps to infinitime to sync them up again after the steps have been lost. But I don't see a way to do that with itd. 

### Version

1.8.0

### Companion app

gadgetbridge

**Comment by Riksu9000** [comment] 2022-04-05 17:41
Duplicate of #493.

**Closed by Riksu9000** 2022-04-05 17:41 UTC
Labels: bug
