### ISSUE TITLE
Heartbeat sensor turns off when display turns off

### ISSUE THREAD

**Issue by mvdkleijn** [InfiniTimeOrg/InfiniTime#1909] opened 2023-11-09 09:00 UTC
### Verification

- [X] I searched for similar bug reports (including closed issues) and found none was relevant.

### What happened?

With heatbeat app turned on, exiting all screens so display turns off causes heartbeat sensor to disable

### What should happen instead?

Heartbeat sensor should keep running

### Reproduction steps

Turn on heartbeat sensor app.
Exit using button.
Verify heart icon is displayed on main screen.
Use physical button to turn off screen.
See green heartbeat light turn off.

### Version

1.13.0

### Companion app

Gadgetbridge 0.76.1

**Comment by FintasticMan** [comment] 2023-11-09 09:21
Duplicate of #183.

**Closed by FintasticMan** 2023-11-09 09:21 UTC
Labels: bug
